/// TODO: These should be automatically generated by Cmake
#include "asan/asan_hooks.h"
#include "tsan/tsan_hooks.h"

#define XSAN_HOOKS_EXEC(FUNC, ...)                                         \
  do {                                                                     \
    XsanHooksSanitizerTraits<XsanHooksSanitizer::Asan>::FUNC(__VA_ARGS__); \
    XsanHooksSanitizerTraits<XsanHooksSanitizer::Tsan>::FUNC(__VA_ARGS__); \
  } while (0)

#define XSAN_HOOKS_EXEC_REDUCE(RES, RED, FUNC, ...)                          \
  do {                                                                       \
    RES = RED(RES, XsanHooksSanitizerTraits<XsanHooksSanitizer::Asan>::FUNC( \
                       __VA_ARGS__));                                        \
    RES = RED(RES, XsanHooksSanitizerTraits<XsanHooksSanitizer::Tsan>::FUNC( \
                       __VA_ARGS__));                                        \
  } while (0)

#define XSAN_HOOKS_DEFINE_VAR(VAR)                              \
  XsanHooksSanitizerTraits<XsanHooksSanitizer::Asan>::VAR asan; \
  XsanHooksSanitizerTraits<XsanHooksSanitizer::Tsan>::VAR tsan;

#define XSAN_HOOKS_DEFINE_VAR_CVT(VAR)                                      \
  operator const XsanHooksSanitizerTraits<XsanHooksSanitizer::Asan>::VAR&() \
      const {                                                               \
    return asan;                                                            \
  }                                                                         \
  operator const XsanHooksSanitizerTraits<XsanHooksSanitizer::Tsan>::VAR&() \
      const {                                                               \
    return tsan;                                                            \
  }

#define XSAN_HOOKS_INIT_VAR(...) \
  asan(__VA_ARGS__), tsan(__VA_ARGS__)
