# generate xsan_hooks_gen.h automatically

include(xsan_config.cmake OPTIONAL RESULT_VARIABLE XSAN_CONFIG_INCLUDED)
if(NOT DEFINED XSAN_DELEGATED_SANITIZERS)
    if(NOT XSAN_CONFIG_INCLUDED)
        message(WARNING "xsan_config.cmake was not found. XSAN_DELEGATED_SANITIZERS is not defined and will be treated as empty.")
    else()
        message(WARNING "xsan_config.cmake was found, but it does not define the XSAN_DELEGATED_SANITIZERS variable. It will be treated as empty.")
    endif()
    set(XSAN_DELEGATED_SANITIZERS "") 
endif()
set(XSAN_HOOKS_HEADER "${CMAKE_CURRENT_SOURCE_DIR}/xsan_hooks_gen.h") 
if(EXISTS "${XSAN_HOOKS_HEADER}")
  file(REMOVE "${XSAN_HOOKS_HEADER}")
endif()

set(XSAN_HOOKS_CONTENT "/// Auto-generated by CMake. Only should be included by xsan_hooks_dispatch.h
#pragma once

#define XSAN_HOOKS_TYPE(SAN) \\
  ::__xsan::XsanHooksSanitizerImpl<::__xsan::XsanHooksSanitizer::SAN>::Hooks

// --------------------- Generated Part 1 ------------------------------------------
") 

# // --------------------- Generate Part 1 ------------------------------------------
set(SANITIZER_MACRO_TEMPLATE [=[

#if XSAN_CONTAINS_$SUBSAN_MACRO_NAME$
#  include "$SUBSAN_HOOK_HEADER_FILE_PATH$"
#  define XSAN_HOOKS_EXEC_$SUBSAN_MACRO_NAME$(FUNC, ...) \\
    XSAN_HOOKS_TYPE($SUBSAN_ENUM_NAME$)::FUNC(__VA_ARGS__)
#  define XSAN_HOOKS_EXEC_REDUCE_$SUBSAN_MACRO_NAME$(RES, RED, FUNC, ...) \\
    RES = RED(RES, XSAN_HOOKS_EXEC_$SUBSAN_MACRO_NAME$(FUNC, __VA_ARGS__))
#  define XSAN_HOOKS_DEFINE_VAR_$SUBSAN_MACRO_NAME$(VAR) XSAN_HOOKS_TYPE($SUBSAN_ENUM_NAME$)::VAR $SUBSAN_VAR_NAME$;
#  define XSAN_HOOKS_DEFINE_VAR_CVT_$SUBSAN_MACRO_NAME$(VAR)                                \\
    __attribute__((always_inline)) operator const XSAN_HOOKS_TYPE(           \\
        $SUBSAN_ENUM_NAME$)::VAR &() const {                                               \\
      return $SUBSAN_VAR_NAME$;                                                           \\
    }                                                                        \\
    __attribute__((always_inline)) operator XSAN_HOOKS_TYPE($SUBSAN_ENUM_NAME$)::VAR &() { \\
      return $SUBSAN_VAR_NAME$;                                                           \\
    }
#  define XSAN_HOOKS_DEFINE_PTR_VAR_$SUBSAN_MACRO_NAME$(NAME, VAR)                          \\
    __attribute__((always_inline)) operator XSAN_HOOKS_TYPE($SUBSAN_ENUM_NAME$)::VAR *() { \\
      return ptr ? &ptr->$SUBSAN_VAR_NAME$ : nullptr;                                     \\
    }                                                                        
#    define XSAN_HOOKS_INIT_VAR_$SUBSAN_MACRO_NAME$(...) , $SUBSAN_VAR_NAME$(__VA_ARGS__)
#  define XSAN_HOOKS_ASSIGN_VAR_$SUBSAN_MACRO_NAME$(FUNC, ...) \\
    $SUBSAN_VAR_NAME$ = XSAN_HOOKS_EXEC_$SUBSAN_MACRO_NAME$(FUNC, __VA_ARGS__);
#  define XSAN_HOOKS_CHECK_IMPL_$SUBSAN_MACRO_NAME$ XSAN_HOOKS_CHECK_IMPL($SUBSAN_ENUM_NAME$)
#else
#  define XSAN_HOOKS_EXEC_$SUBSAN_MACRO_NAME$(FUNC, ...)
#  define XSAN_HOOKS_EXEC_REDUCE_$SUBSAN_MACRO_NAME$(RES, RED, FUNC, ...)
#  define XSAN_HOOKS_DEFINE_VAR_$SUBSAN_MACRO_NAME$(VAR)
#  define XSAN_HOOKS_DEFINE_VAR_CVT_$SUBSAN_MACRO_NAME$(VAR)
#  define XSAN_HOOKS_DEFINE_PTR_VAR_$SUBSAN_MACRO_NAME$(NAME, VAR)
#  define XSAN_HOOKS_INIT_VAR_$SUBSAN_MACRO_NAME$(...)
#  define XSAN_HOOKS_ASSIGN_VAR_$SUBSAN_MACRO_NAME$(FUNC, ...)
#  define XSAN_HOOKS_CHECK_IMPL_$SUBSAN_MACRO_NAME$
#endif

]=]) 

foreach(SanitizerName ${XSAN_DELEGATED_SANITIZERS})
    set(CURRENT_SANITIZER_NAME_ORIGINAL ${SanitizerName}) # eg. Asan, Tsan
    string(TOUPPER ${SanitizerName} CURRENT_MACRO_NAME_REPLACEMENT) # eg. ASAN, TSAN
    string(TOLOWER ${SanitizerName} CURRENT_VAR_NAME_REPLACEMENT)   # eg. asan, tsan
    
    set(CURRENT_HOOK_HEADER_PATH_REPLACEMENT "${CURRENT_VAR_NAME_REPLACEMENT}/${CURRENT_VAR_NAME_REPLACEMENT}_hooks.h") # eg. "asan/asan_hooks.h"
    set(CURRENT_ENUM_NAME_REPLACEMENT ${CURRENT_SANITIZER_NAME_ORIGINAL}) # eg. Asan, Tsan

    # replace the macro names in the template
    set(CURRENT_SANITIZER_CODE_BLOCK "${SANITIZER_MACRO_TEMPLATE}")

    string(REPLACE "$SUBSAN_MACRO_NAME$" "${CURRENT_MACRO_NAME_REPLACEMENT}" CURRENT_SANITIZER_CODE_BLOCK "${CURRENT_SANITIZER_CODE_BLOCK}")
    string(REPLACE "$SUBSAN_HOOK_HEADER_FILE_PATH$" "${CURRENT_HOOK_HEADER_PATH_REPLACEMENT}" CURRENT_SANITIZER_CODE_BLOCK "${CURRENT_SANITIZER_CODE_BLOCK}")
    string(REPLACE "$SUBSAN_ENUM_NAME$" "${CURRENT_ENUM_NAME_REPLACEMENT}" CURRENT_SANITIZER_CODE_BLOCK "${CURRENT_SANITIZER_CODE_BLOCK}")
    string(REPLACE "$SUBSAN_VAR_NAME$" "${CURRENT_VAR_NAME_REPLACEMENT}" CURRENT_SANITIZER_CODE_BLOCK "${CURRENT_SANITIZER_CODE_BLOCK}")

    extend_string_if(TRUE "${CURRENT_SANITIZER_CODE_BLOCK}" XSAN_HOOKS_CONTENT)
endforeach()


# // --------------------- Generate Part 2 ------------------------------------------
extend_string_if(TRUE "// --------------------- Generated Part 2 ------------------------------------------\n" XSAN_HOOKS_CONTENT)

# generate XSAN_HOOKS_EXEC macro
set(XSAN_HOOKS_EXEC_INNER_CALLS "")
if(XSAN_DELEGATED_SANITIZERS)
  foreach(SanitizerName ${XSAN_DELEGATED_SANITIZERS})
    string(TOUPPER ${SanitizerName} SanitizerNameUpper)
    set(XSAN_HOOKS_EXEC_INNER_CALLS "${XSAN_HOOKS_EXEC_INNER_CALLS}    XSAN_HOOKS_EXEC_${SanitizerNameUpper}(FUNC, __VA_ARGS__); \\\n")
  endforeach()
endif()
set(XSAN_HOOKS_EXEC_MACRO_DEFINITION [=[
#define XSAN_HOOKS_EXEC(FUNC, ...)           \\
  do {                                       \\
${XSAN_HOOKS_EXEC_INNER_CALLS}  } while (0)

]=])
extend_string_if(TRUE "${XSAN_HOOKS_EXEC_MACRO_DEFINITION}" XSAN_HOOKS_CONTENT)

# generate XSAN_HOOKS_EXEC_REDUCE macro
set(XSAN_HOOKS_EXEC_REDUCE_INNER_CALLS "")
if(XSAN_DELEGATED_SANITIZERS)
  foreach(SanitizerName ${XSAN_DELEGATED_SANITIZERS})
    string(TOUPPER ${SanitizerName} SanitizerNameUpper)
    set(XSAN_HOOKS_EXEC_REDUCE_INNER_CALLS "${XSAN_HOOKS_EXEC_REDUCE_INNER_CALLS}    XSAN_HOOKS_EXEC_REDUCE_${SanitizerNameUpper}(RES, RED, FUNC, __VA_ARGS__); \\\n")
  endforeach()
endif()
set(XSAN_HOOKS_EXEC_REDUCE_MACRO_DEFINITION [=[
#define XSAN_HOOKS_EXEC_REDUCE(RES, RED, FUNC, ...)           \\
  do {                                                        \\
${XSAN_HOOKS_EXEC_REDUCE_INNER_CALLS}  } while (0)

]=])
extend_string_if(TRUE "${XSAN_HOOKS_EXEC_REDUCE_MACRO_DEFINITION}" XSAN_HOOKS_CONTENT)

# generate XSAN_HOOKS_DEFINE_VAR macro
set(CURRENT_XSAN_HOOKS_DEFINE_VAR_MACRO_OUTPUT [=[
// Placeholder has no effect, it is only used to facilitate the writing of macros.
#define XSAN_HOOKS_DEFINE_VAR(VAR) \\
  struct {                         \\
  } placeholder;                   ]=])
set(SANITIZER_LIST_FOR_DEFINE_VAR ${XSAN_DELEGATED_SANITIZERS})
foreach(SanitizerName ${SANITIZER_LIST_FOR_DEFINE_VAR})
    string(TOUPPER ${SanitizerName} SanitizerNameUpper)
    extend_string_if(TRUE [=[\\\\\
 ]=] CURRENT_XSAN_HOOKS_DEFINE_VAR_MACRO_OUTPUT)    
    extend_string_if(TRUE [=[ XSAN_HOOKS_DEFINE_VAR_${SanitizerNameUpper}(VAR)  ]=] CURRENT_XSAN_HOOKS_DEFINE_VAR_MACRO_OUTPUT)
endforeach()
extend_string_if(TRUE [=[


]=] CURRENT_XSAN_HOOKS_DEFINE_VAR_MACRO_OUTPUT)
extend_string_if(TRUE "${CURRENT_XSAN_HOOKS_DEFINE_VAR_MACRO_OUTPUT}" XSAN_HOOKS_CONTENT)

# generate XSAN_HOOKS_DEFINE_VAR_CVT macro
set(CURRENT_XSAN_HOOKS_DEFINE_VAR_CVT_MACRO_OUTPUT [=[
#define XSAN_HOOKS_DEFINE_VAR_CVT(VAR) ]=]) 
set(SANITIZER_LIST_FOR_DEFINE_VAR_CVT ${XSAN_DELEGATED_SANITIZERS})
foreach(SanitizerName ${SANITIZER_LIST_FOR_DEFINE_VAR_CVT})
    string(TOUPPER ${SanitizerName} SanitizerNameUpper)
    extend_string_if(TRUE [=[\\\\\\
  XSAN_HOOKS_DEFINE_VAR_CVT_${SanitizerNameUpper}(VAR)  ]=] CURRENT_XSAN_HOOKS_DEFINE_VAR_CVT_MACRO_OUTPUT)
endforeach()
extend_string_if(TRUE [=[


]=] CURRENT_XSAN_HOOKS_DEFINE_VAR_CVT_MACRO_OUTPUT)
extend_string_if(TRUE "${CURRENT_XSAN_HOOKS_DEFINE_VAR_CVT_MACRO_OUTPUT}" XSAN_HOOKS_CONTENT)

# generate XSAN_HOOKS_DEFINE_VAR macro
if(XSAN_DELEGATED_SANITIZERS)
  foreach(SanitizerName ${XSAN_DELEGATED_SANITIZERS})
    string(TOUPPER ${SanitizerName} SanitizerNameUpper)
    set(XSAN_HOOKS_DEFINE_PTR_VAR_INNER_DEFINES "${XSAN_HOOKS_DEFINE_PTR_VAR_INNER_DEFINES}    XSAN_HOOKS_DEFINE_PTR_VAR_${SanitizerNameUpper}(NAME, VAR) \\\n")
  endforeach()
endif()
set(XSAN_HOOKS_DEFINE_PTR_VAR_MACRO_DEFINITION [=[
#define XSAN_HOOKS_DEFINE_PTR_VAR(NAME, VAR)  \\
  struct Ptr {                                \\
    NAME *ptr;                                \\
${XSAN_HOOKS_DEFINE_PTR_VAR_INNER_DEFINES}  };

]=])
extend_string_if(TRUE "${XSAN_HOOKS_DEFINE_PTR_VAR_MACRO_DEFINITION}" XSAN_HOOKS_CONTENT)

# generate XSAN_HOOKS_INIT_VAR macro
set(CURRENT_XSAN_HOOKS_INIT_VAR_MACRO_OUTPUT [=[
#define XSAN_HOOKS_INIT_VAR(...)]=])
list(LENGTH XSAN_DELEGATED_SANITIZERS NUM_SANITIZERS_FOR_INIT_VAR)
# if has any sanitizer, add "\"after #define line
if(NUM_SANITIZERS_FOR_INIT_VAR GREATER 0)
    extend_string_if(TRUE [=[ \\\\\
  placeholder()]=] CURRENT_XSAN_HOOKS_INIT_VAR_MACRO_OUTPUT)
    set(BODY_CONTENT_FOR_INIT_VAR "")
    foreach(SanitizerName ${XSAN_DELEGATED_SANITIZERS})
      string(TOUPPER ${SanitizerName} SanitizerNameUpper)
      set(SANITIZER_SPECIFIC_CALL "XSAN_HOOKS_INIT_VAR_${SanitizerNameUpper}(__VA_ARGS__)")
      set(BODY_CONTENT_FOR_INIT_VAR "${BODY_CONTENT_FOR_INIT_VAR} ${SANITIZER_SPECIFIC_CALL}")
    endforeach()
    extend_string_if(TRUE "${BODY_CONTENT_FOR_INIT_VAR}" CURRENT_XSAN_HOOKS_INIT_VAR_MACRO_OUTPUT)
endif()
extend_string_if(TRUE [=[


]=] CURRENT_XSAN_HOOKS_INIT_VAR_MACRO_OUTPUT)
extend_string_if(TRUE "${CURRENT_XSAN_HOOKS_INIT_VAR_MACRO_OUTPUT}" XSAN_HOOKS_CONTENT)

# generate XSAN_HOOKS_ASSIGN_VAR macro
set(CURRENT_XSAN_HOOKS_ASSIGN_VAR_MACRO_OUTPUT [=[
#define XSAN_HOOKS_ASSIGN_VAR(FUNC, ...)        ]=])
set(SANITIZER_LIST_FOR_ASSIGN_VAR ${XSAN_DELEGATED_SANITIZERS})
foreach(SanitizerName ${SANITIZER_LIST_FOR_ASSIGN_VAR})
    string(TOUPPER ${SanitizerName} SanitizerNameUpper)
    extend_string_if(TRUE [=[ \\\\\
  XSAN_HOOKS_ASSIGN_VAR_${SanitizerNameUpper}(FUNC, __VA_ARGS__);]=] CURRENT_XSAN_HOOKS_ASSIGN_VAR_MACRO_OUTPUT)
endforeach()
extend_string_if(TRUE [=[


]=] CURRENT_XSAN_HOOKS_ASSIGN_VAR_MACRO_OUTPUT)
extend_string_if(TRUE "${CURRENT_XSAN_HOOKS_ASSIGN_VAR_MACRO_OUTPUT}" XSAN_HOOKS_CONTENT)

# generate XSAN_HOOKS_CHECK_IMPL_XXXX macro
set(TMP_XSAN_HOOKS_CHECK_IMPL_CALLS_STRING "")
if(XSAN_DELEGATED_SANITIZERS)
    set(SANITIZER_LIST_FOR_CHECK_IMPL ${XSAN_DELEGATED_SANITIZERS})
    foreach(SanitizerName ${SANITIZER_LIST_FOR_CHECK_IMPL})
        string(TOUPPER ${SanitizerName} SanitizerNameUpper)
        extend_string_if(TRUE [=[XSAN_HOOKS_CHECK_IMPL_${SanitizerNameUpper}
]=] TMP_XSAN_HOOKS_CHECK_IMPL_CALLS_STRING)
    endforeach()
    extend_string_if(TRUE "${TMP_XSAN_HOOKS_CHECK_IMPL_CALLS_STRING}" XSAN_HOOKS_CONTENT)
endif()

file(WRITE "${XSAN_HOOKS_HEADER}" "${XSAN_HOOKS_CONTENT}")
message(STATUS "Generated XSan hooks header: ${XSAN_HOOKS_HEADER}")
