/// TODO: These should be automatically generated by Cmake
#pragma once

#include "asan/asan_hooks.h"
#include "tsan/tsan_hooks.h"

// This macro is just for shortening the code for now, since this file will be
// automatically generated by CMake in the future.
#define XSAN_HOOKS_TYPE(SAN) \
  ::__xsan::XsanHooksSanitizerImpl<::__xsan::XsanHooksSanitizer::SAN>::Hooks

#define XSAN_HOOKS_EXEC(FUNC, ...)            \
  do {                                        \
    XSAN_HOOKS_TYPE(Asan)::FUNC(__VA_ARGS__); \
    XSAN_HOOKS_TYPE(Tsan)::FUNC(__VA_ARGS__); \
  } while (0)

#define XSAN_HOOKS_EXEC_REDUCE(RES, RED, FUNC, ...)           \
  do {                                                        \
    RES = RED(RES, XSAN_HOOKS_TYPE(Asan)::FUNC(__VA_ARGS__)); \
    RES = RED(RES, XSAN_HOOKS_TYPE(Tsan)::FUNC(__VA_ARGS__)); \
  } while (0)

#define XSAN_HOOKS_DEFINE_VAR(VAR) \
  XSAN_HOOKS_TYPE(Asan)::VAR asan; \
  XSAN_HOOKS_TYPE(Tsan)::VAR tsan;

#define XSAN_HOOKS_DEFINE_VAR_CVT(VAR)                                         \
  __attribute__((always_inline)) operator const XSAN_HOOKS_TYPE(Asan)::VAR &() \
      const {                                                                  \
    return asan;                                                               \
  }                                                                            \
  __attribute__((always_inline)) operator const XSAN_HOOKS_TYPE(Tsan)::VAR &() \
      const {                                                                  \
    return tsan;                                                               \
  }                                                                            \
  __attribute__((always_inline)) operator XSAN_HOOKS_TYPE(Asan)::VAR &() {     \
    return asan;                                                               \
  }                                                                            \
  __attribute__((always_inline)) operator XSAN_HOOKS_TYPE(Tsan)::VAR &() {     \
    return tsan;                                                               \
  }

#define XSAN_HOOKS_DEFINE_PTR_VAR(NAME, VAR)                                 \
  struct Ptr {                                                               \
    NAME *ptr;                                                               \
    __attribute__((always_inline)) operator XSAN_HOOKS_TYPE(Asan)::VAR *() { \
      return ptr ? &ptr->asan : nullptr;                                     \
    }                                                                        \
    __attribute__((always_inline)) operator XSAN_HOOKS_TYPE(Tsan)::VAR *() { \
      return ptr ? &ptr->tsan : nullptr;                                     \
    }                                                                        \
  };

#define XSAN_HOOKS_INIT_VAR(...) asan(__VA_ARGS__), tsan(__VA_ARGS__)

#define XSAN_HOOKS_ASSIGN_VAR(FUNC, ...)           \
  asan = XSAN_HOOKS_TYPE(Asan)::FUNC(__VA_ARGS__); \
  tsan = XSAN_HOOKS_TYPE(Tsan)::FUNC(__VA_ARGS__);

XSAN_HOOKS_CHECK_IMPL(Asan)
XSAN_HOOKS_CHECK_IMPL(Tsan)
