set(TSAN_LIT_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})

set(TSAN_TEST_DEPS ${SANITIZER_COMMON_LIT_TEST_DEPS})
if(${COMPILER_RT_DEFAULT_TARGET_ARCH} MATCHES "(x86_64|s390x)")
  list(APPEND TSAN_TEST_DEPS GotsanRuntimeCheck)
endif()
if(NOT COMPILER_RT_STANDALONE_BUILD)
  list(APPEND TSAN_TEST_DEPS tsan)
endif()

# TODO: add libc++ support
set(TSAN_HAS_LIBCXX False)
# if(COMPILER_RT_LIBCXX_PATH AND
#    COMPILER_RT_LIBCXXABI_PATH AND
#    COMPILER_RT_TEST_COMPILER_ID STREQUAL "Clang"
#    AND NOT APPLE AND NOT ANDROID)
#   list(APPEND TSAN_TEST_DEPS libcxx_tsan)
#   set(TSAN_HAS_LIBCXX True)
# else()
#   set(TSAN_HAS_LIBCXX False)
# endif()

set(TSAN_DYNAMIC_TEST_DEPS ${TSAN_TEST_DEPS})
set(TSAN_TESTSUITES)
set(TSAN_DYNAMIC_TESTSUITES)

if (NOT DEFINED TSAN_TEST_DEFLAKE_THRESHOLD)
  set(TSAN_TEST_DEFLAKE_THRESHOLD "10")
endif()