//===-- xsan_platform_x64_48.h: Auto-generated by SMT solver --------------===//
//
// Generated Time: 2025-10-20T15:51:02.517729Z
// Platform: MappingX64_48
// Generated by:
//
// ./gen_mapping_via_z3.py --output=header --platform=x64_48
//
//===----------------------------------------------------------------------===/
//
// NOTE: This file was generated by an SMT solver; do not edit manually unless
// you know what you are doing.
//
//===----------------------------------------------------------------------===/

#pragma once

/*
C/C++ on MappingX64_48 Memory Layout:

Complete Memory Layout (sorted by address):
--------------------------------------------------------------------------------
000000000000 - 00007fff7000: LoApp (for ASan) (2.00 GB)
00007fff7000 - 00007fff8000: - gap (4 KB)
00007fff8000 - 00008fff7000: -- ASan Shadow (LoApp) (256.00 MB)
000000000000 - 010000000000: LoApp (1 TB)
010000000000 - 02008fff7000: - gap (1.00 TB)
02008fff7000 - 10007fff8000: -- ASan Shadow (Rest) (14.00 TB)
10007fff8000 - 150000000000: - gap (5.00 TB)
150000000000 - 1a0000000000: -- MSan Shadow (MidApp) (5 TB)
1a0000000000 - 1c0000000000: -- TSan Shadow (LoApp) (2 TB)
1c0000000000 - 1e0000000000: - gap (2 TB)
1e0000000000 - 220000000000: -- TSan Shadow (Heap) (4 TB)
220000000000 - 240000000000: -- MSan Shadow (Heap) (2 TB)
240000000000 - 2e0000000000: -- TSan Shadow (MidApp) (10 TB)
2e0000000000 - 3a0000000000: -- TSan Shadow (HiApp) (12 TB)
3a0000000000 - 400000000000: -- MSan Shadow (HiApp) (6 TB)
400000000000 - 410000000000: -- MSan Shadow (LoApp) (1 TB)
410000000000 - 440000000000: - gap (3 TB)
440000000000 - 490000000000: -- MSan Origin (MidApp) (5 TB)
490000000000 - 510000000000: - gap (8 TB)
510000000000 - 530000000000: -- MSan Origin (Heap) (2 TB)
530000000000 - 550000000000: - gap (2 TB)
550000000000 - 5a0000000000: MidApp (5 TB)
5a0000000000 - 620000000000: - gap (8 TB)
620000000000 - 640000000000: Heap (2 TB)
640000000000 - 690000000000: - gap (5 TB)
690000000000 - 6f0000000000: -- MSan Origin (HiApp) (6 TB)
6f0000000000 - 700000000000: -- MSan Origin (LoApp) (1 TB)
700000000000 - 708000000000: -- TSan Meta (LoApp) (512 GB)
708000000000 - 710000000000: - gap (512 GB)
710000000000 - 720000000000: -- TSan Meta (Heap) (1 TB)
720000000000 - 728000000000: - gap (512 GB)
728000000000 - 750000000000: -- TSan Meta (MidApp) (2.50 TB)
750000000000 - 780000000000: -- TSan Meta (HiApp) (3 TB)
780000000000 - 7a0000000000: - gap (2 TB)
7a0000000000 - 800000000000: HiApp (6 TB)

*/
struct MappingX64_48 {
  static constexpr const uintptr kHeapMemBeg = 0x6200'0000'0000ull;
  static constexpr const uintptr kHeapMemEnd = 0x6400'0000'0000ull;
  static constexpr const uintptr kLoAppMemBeg = 0x0000'0000'0000ull;
  static constexpr const uintptr kLoAppMemEnd = 0x0100'0000'0000ull;
  // Used only for ASan's shadow calculation
  static constexpr const uintptr kAsanLoAppMemEnd = 0x0000'7fff'7000ull;
  static constexpr const uintptr kMidAppMemBeg = 0x5500'0000'0000ull;
  static constexpr const uintptr kMidAppMemEnd = 0x5a00'0000'0000ull;
  static constexpr const uintptr kHiAppMemBeg = 0x7a00'0000'0000ull;
  static constexpr const uintptr kHiAppMemEnd = 0x8000'0000'0000ull;
  static constexpr const uintptr kVdsoBeg = 0xf000'0000'0000'0000ull;

  // ASan Parameters:
  static constexpr const uintptr kAsanShadowOffset = 0x0000'7fff'8000ull;
  static constexpr const uintptr kAsanShadowScale = 3;

  // MSan Parameters:
  static constexpr const uintptr kMSanShadowXor = 0x4000'0000'0000ull;
  static constexpr const uintptr kMSanShadowAdd = 0x2f00'0000'0000ull;

  // TSan Parameters:
  static constexpr const uintptr kTsanShadowXor = 0x0000'0000'0000ull;
  static constexpr const uintptr kTsanShadowAdd = 0x1a00'0000'0000ull;
  static constexpr const uintptr kTsanShadowMsk = 0x7000'0000'0000ull;
  static constexpr const uintptr kTsanMetaShadowBeg = 0x7000'0000'0000ull;
  static constexpr const uintptr kTsanMetaShadowEnd = 0x7800'0000'0000ull;
  static constexpr const uintptr kTsanShadowBeg = 0x1a00'0000'0000ull;
  static constexpr const uintptr kTsanShadowEnd = 0x3a00'0000'0000ull;

  // All Memory Regions to Map (just for reference as sanitizer might change the
  // mapping dynamically)
  static constexpr const MemRegion kRegions[] = {
      {0x0000'0000'0000ull, 0x0000'7fff'7000ull, RegionType::App,
       "LoApp (for ASan)"},
      {0x0000'7fff'8000ull, 0x0000'8fff'7000ull, RegionType::Shadow,
       "ASan Shadow (LoApp)"},
      {0x0000'0000'0000ull, 0x0100'0000'0000ull, RegionType::App, "LoApp"},
      {0x0200'8fff'7000ull, 0x1000'7fff'8000ull, RegionType::Shadow,
       "ASan Shadow (Rest)"},
      {0x1500'0000'0000ull, 0x1a00'0000'0000ull, RegionType::Shadow,
       "MSan Shadow (MidApp)"},
      {0x1a00'0000'0000ull, 0x1c00'0000'0000ull, RegionType::Shadow,
       "TSan Shadow (LoApp)"},
      {0x1e00'0000'0000ull, 0x2200'0000'0000ull, RegionType::Shadow,
       "TSan Shadow (Heap)"},
      {0x2200'0000'0000ull, 0x2400'0000'0000ull, RegionType::Shadow,
       "MSan Shadow (Heap)"},
      {0x2400'0000'0000ull, 0x2e00'0000'0000ull, RegionType::Shadow,
       "TSan Shadow (MidApp)"},
      {0x2e00'0000'0000ull, 0x3a00'0000'0000ull, RegionType::Shadow,
       "TSan Shadow (HiApp)"},
      {0x3a00'0000'0000ull, 0x4000'0000'0000ull, RegionType::Shadow,
       "MSan Shadow (HiApp)"},
      {0x4000'0000'0000ull, 0x4100'0000'0000ull, RegionType::Shadow,
       "MSan Shadow (LoApp)"},
      {0x4400'0000'0000ull, 0x4900'0000'0000ull, RegionType::Shadow,
       "MSan Origin (MidApp)"},
      {0x5100'0000'0000ull, 0x5300'0000'0000ull, RegionType::Shadow,
       "MSan Origin (Heap)"},
      {0x5500'0000'0000ull, 0x5a00'0000'0000ull, RegionType::App, "MidApp"},
      {0x6200'0000'0000ull, 0x6400'0000'0000ull, RegionType::App, "Heap"},
      {0x6900'0000'0000ull, 0x6f00'0000'0000ull, RegionType::Shadow,
       "MSan Origin (HiApp)"},
      {0x6f00'0000'0000ull, 0x7000'0000'0000ull, RegionType::Shadow,
       "MSan Origin (LoApp)"},
      {0x7000'0000'0000ull, 0x7080'0000'0000ull, RegionType::Shadow,
       "TSan Meta (LoApp)"},
      {0x7100'0000'0000ull, 0x7200'0000'0000ull, RegionType::Shadow,
       "TSan Meta (Heap)"},
      {0x7280'0000'0000ull, 0x7500'0000'0000ull, RegionType::Shadow,
       "TSan Meta (MidApp)"},
      {0x7500'0000'0000ull, 0x7800'0000'0000ull, RegionType::Shadow,
       "TSan Meta (HiApp)"},
      {0x7a00'0000'0000ull, 0x8000'0000'0000ull, RegionType::App, "HiApp"},
  };
};
