//===-- xsan_platform_aarch64_48.h: Auto-generated by SMT solver ----------===//
//
// Generated Time: 2025-10-20T15:50:37.613613Z
// Platform: MappingAarch64_48
// Generated by:
//
// ./gen_mapping_via_z3.py --output=header --platform=aarch64_48
//
//===----------------------------------------------------------------------===/
//
// NOTE: This file was generated by an SMT solver; do not edit manually unless
// you know what you are doing.
//
//===----------------------------------------------------------------------===/

#pragma once

/*
C/C++ on MappingAarch64_48 Memory Layout:

Complete Memory Layout (sorted by address):
--------------------------------------------------------------------------------
000000000000 - 000ffffff000: LoApp (for ASan) (64.00 GB)
000ffffff000 - 001000000000: - gap (4 KB)
001000000000 - 001200000000: -- ASan Shadow (LoApp) (8 GB)
000000000000 - 010000000000: LoApp (1 TB)
010000000000 - 041200000000: - gap (3.07 TB)
041200000000 - 201000000000: -- ASan Shadow (Rest) (27.99 TB)
201000000000 - 3aaa00000000: - gap (26.60 TB)
3aaa00000000 - 3c0000000000: -- MSan Shadow (MidApp) (1.34 TB)
3c0000000000 - 480000000000: - gap (12 TB)
480000000000 - 4a0000000000: -- MSan Shadow (Heap) (2 TB)
4a0000000000 - 66aa00000000: - gap (28.66 TB)
66aa00000000 - 680000000000: -- MSan Origin (MidApp) (1.34 TB)
680000000000 - 6c0000000000: - gap (4 TB)
6c0000000000 - 700000000000: -- MSan Shadow (HiApp) (4 TB)
700000000000 - 740000000000: - gap (4 TB)
740000000000 - 760000000000: -- MSan Origin (Heap) (2 TB)
760000000000 - 900000000000: - gap (26 TB)
900000000000 - 910000000000: -- MSan Shadow (LoApp) (1 TB)
910000000000 - 980000000000: - gap (7 TB)
980000000000 - 9c0000000000: -- MSan Origin (HiApp) (4 TB)
9c0000000000 - aaaa00000000: - gap (14.66 TB)
aaaa00000000 - ac0000000000: MidApp (1.34 TB)
ac0000000000 - af0000000000: - gap (3 TB)
af0000000000 - b10000000000: -- TSan Shadow (LoApp) (2 TB)
b10000000000 - bc0000000000: - gap (11 TB)
bc0000000000 - bd0000000000: -- MSan Origin (LoApp) (1 TB)
bd0000000000 - bf0000000000: - gap (2 TB)
bf0000000000 - c30000000000: -- TSan Shadow (Heap) (4 TB)
c30000000000 - c45400000000: - gap (1.33 TB)
c45400000000 - c70000000000: -- TSan Shadow (MidApp) (2.67 TB)
c70000000000 - cf0000000000: -- TSan Shadow (HiApp) (8 TB)
cf0000000000 - d00000000000: - gap (1 TB)
d00000000000 - d08000000000: -- TSan Meta (LoApp) (512 GB)
d08000000000 - d40000000000: - gap (3.50 TB)
d40000000000 - d50000000000: -- TSan Meta (Heap) (1 TB)
d50000000000 - d55500000000: - gap (340 GB)
d55500000000 - d60000000000: -- TSan Meta (MidApp) (684 GB)
d60000000000 - d80000000000: -- TSan Meta (HiApp) (2 TB)
d80000000000 - da0000000000: Heap (2 TB)
da0000000000 - fc0000000000: - gap (34 TB)
fc0000000000 - 1000000000000: HiApp (4 TB)

*/
struct MappingAarch64_48 {
  static constexpr const uintptr kHeapMemBeg = 0xd800'0000'0000ull;
  static constexpr const uintptr kHeapMemEnd = 0xda00'0000'0000ull;
  static constexpr const uintptr kLoAppMemBeg = 0x0000'0000'0000ull;
  static constexpr const uintptr kLoAppMemEnd = 0x0100'0000'0000ull;
  // Used only for ASan's shadow calculation
  static constexpr const uintptr kAsanLoAppMemEnd = 0x000f'ffff'f000ull;
  static constexpr const uintptr kMidAppMemBeg = 0xaaaa'0000'0000ull;
  static constexpr const uintptr kMidAppMemEnd = 0xac00'0000'0000ull;
  static constexpr const uintptr kHiAppMemBeg = 0xfc00'0000'0000ull;
  static constexpr const uintptr kHiAppMemEnd = 0x1'0000'0000'0000ull;
  static constexpr const uintptr kVdsoBeg = 0xf'fff0'0000'0000ull;

  // ASan Parameters:
  static constexpr const uintptr kAsanShadowOffset = 0x0010'0000'0000ull;
  static constexpr const uintptr kAsanShadowScale = 3;

  // MSan Parameters:
  static constexpr const uintptr kMSanShadowXor = 0x9000'0000'0000ull;
  static constexpr const uintptr kMSanShadowAdd = 0x2c00'0000'0000ull;

  // TSan Parameters:
  static constexpr const uintptr kTsanShadowXor = 0x0000'0000'0000ull;
  static constexpr const uintptr kTsanShadowAdd = 0xaf00'0000'0000ull;
  static constexpr const uintptr kTsanShadowMsk = 0xf000'0000'0000ull;
  static constexpr const uintptr kTsanMetaShadowBeg = 0xd000'0000'0000ull;
  static constexpr const uintptr kTsanMetaShadowEnd = 0xd800'0000'0000ull;
  static constexpr const uintptr kTsanShadowBeg = 0xaf00'0000'0000ull;
  static constexpr const uintptr kTsanShadowEnd = 0xcf00'0000'0000ull;

  // All Memory Regions to Map (just for reference as sanitizer might change the
  // mapping dynamically)
  static constexpr const MemRegion kRegions[] = {
      {0x0000'0000'0000ull, 0x000f'ffff'f000ull, RegionType::App,
       "LoApp (for ASan)"},
      {0x0010'0000'0000ull, 0x0012'0000'0000ull, RegionType::Shadow,
       "ASan Shadow (LoApp)"},
      {0x0000'0000'0000ull, 0x0100'0000'0000ull, RegionType::App, "LoApp"},
      {0x0412'0000'0000ull, 0x2010'0000'0000ull, RegionType::Shadow,
       "ASan Shadow (Rest)"},
      {0x3aaa'0000'0000ull, 0x3c00'0000'0000ull, RegionType::Shadow,
       "MSan Shadow (MidApp)"},
      {0x4800'0000'0000ull, 0x4a00'0000'0000ull, RegionType::Shadow,
       "MSan Shadow (Heap)"},
      {0x66aa'0000'0000ull, 0x6800'0000'0000ull, RegionType::Shadow,
       "MSan Origin (MidApp)"},
      {0x6c00'0000'0000ull, 0x7000'0000'0000ull, RegionType::Shadow,
       "MSan Shadow (HiApp)"},
      {0x7400'0000'0000ull, 0x7600'0000'0000ull, RegionType::Shadow,
       "MSan Origin (Heap)"},
      {0x9000'0000'0000ull, 0x9100'0000'0000ull, RegionType::Shadow,
       "MSan Shadow (LoApp)"},
      {0x9800'0000'0000ull, 0x9c00'0000'0000ull, RegionType::Shadow,
       "MSan Origin (HiApp)"},
      {0xaaaa'0000'0000ull, 0xac00'0000'0000ull, RegionType::App, "MidApp"},
      {0xaf00'0000'0000ull, 0xb100'0000'0000ull, RegionType::Shadow,
       "TSan Shadow (LoApp)"},
      {0xbc00'0000'0000ull, 0xbd00'0000'0000ull, RegionType::Shadow,
       "MSan Origin (LoApp)"},
      {0xbf00'0000'0000ull, 0xc300'0000'0000ull, RegionType::Shadow,
       "TSan Shadow (Heap)"},
      {0xc454'0000'0000ull, 0xc700'0000'0000ull, RegionType::Shadow,
       "TSan Shadow (MidApp)"},
      {0xc700'0000'0000ull, 0xcf00'0000'0000ull, RegionType::Shadow,
       "TSan Shadow (HiApp)"},
      {0xd000'0000'0000ull, 0xd080'0000'0000ull, RegionType::Shadow,
       "TSan Meta (LoApp)"},
      {0xd400'0000'0000ull, 0xd500'0000'0000ull, RegionType::Shadow,
       "TSan Meta (Heap)"},
      {0xd555'0000'0000ull, 0xd600'0000'0000ull, RegionType::Shadow,
       "TSan Meta (MidApp)"},
      {0xd600'0000'0000ull, 0xd800'0000'0000ull, RegionType::Shadow,
       "TSan Meta (HiApp)"},
      {0xd800'0000'0000ull, 0xda00'0000'0000ull, RegionType::App, "Heap"},
      {0xfc00'0000'0000ull, 0x1'0000'0000'0000ull, RegionType::App, "HiApp"},
  };
};
